name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: echo dir
      run : cd EpicUtilites ; dir | % { $_.FullName -replace "C:\\","" }
      
    - name: Restore depende47ncies
      run: cd EpicUtilites ; nuget restore -PackagesDirectory=D:\a\EpicUtilites\EpicUtilites\EpicUtilites\packages

      
    - name: Build
      run: EpicUtilites build --no-restore
    - name: Test
      run: EpicUtilites test --no-build --verbosity normal
